repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
  - id: ruff
    name: ruff
    entry: poetry run ruff . --fix
    language: system
    types: [python]
  - id: mypy
    name: mypy
    entry: poetry run mypy --config-file=pyproject.toml
    language: system
    types: [python]
  - id: conventional-pre-commit
    name: conventional-pre-commit
    entry: conventional-pre-commit
    language: python
    stages: [ commit-msg ]
