name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  release:
    uses: codingones/github-actions-workflows/.github/workflows/semantic-release.github-only.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
